# Generated by Django 2.2 on 2019-05-02 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persion',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('alt_mail', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('employee_ID', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('PI', 'PI'), ('Staff', 'Staff')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent', models.BooleanField(null=True)),
                ('PI', models.CharField(max_length=100)),
                ('card', models.BooleanField(null=True)),
                ('card_PI', models.CharField(max_length=100)),
                ('culture_room', models.BooleanField(null=True)),
                ('culture_room_start', models.DateField()),
                ('culture_room_end', models.DateField()),
                ('EHS_training', models.DateField()),
                ('security_training', models.DateField()),
                ('leave', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Persion')),
            ],
        ),
        migrations.CreateModel(
            name='PI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_date', models.DateField()),
                ('property', models.CharField(choices=[('醫研部', '醫研部'), ('固定', '固定'), ('流動', '流動')], max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('card', models.BooleanField(null=True)),
                ('culture_room', models.BooleanField(null=True)),
                ('hazardous_chemicals', models.BooleanField(null=True)),
                ('toxic_chenicals', models.BooleanField(null=True)),
                ('pre_extension_date', models.DateField()),
                ('pre_extension_result', models.CharField(max_length=100)),
                ('extension_date', models.DateField()),
                ('extension_result', models.CharField(max_length=100)),
                ('return_date', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Persion')),
            ],
        ),
    ]
