# Generated by Django 2.2 on 2019-05-02 07:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive', models.DateField()),
                ('receipt', models.CharField(max_length=50)),
                ('card_ID', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=4)),
                ('card_return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('alt_mail', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=20)),
                ('employee_ID', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('PI', 'PI'), ('Staff', 'Staff')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='pi',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Person'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Person'),
        ),
        migrations.DeleteModel(
            name='Persion',
        ),
        migrations.AddField(
            model_name='card',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Person'),
        ),
    ]
