# Generated by Django 2.2 on 2019-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190502_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alt_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
