# Generated by Django 2.2 on 2019-05-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190502_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
