# Generated by Django 2.2 on 2019-05-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_pi_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pi',
            name='name',
        ),
    ]
