# Generated by Django 2.2 on 2019-05-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_remove_pi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Person'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Person'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Person'),
        ),
    ]
