# Generated by Django 2.2 on 2019-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20190507_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='core_lab',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
