# Generated by Django 2.2 on 2019-06-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_person_core_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='PI',
            field=models.CharField(max_length=50),
        ),
    ]
