# Generated by Django 2.2 on 2019-06-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20190603_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='card_pi',
            field=models.CharField(default='PI', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='pi',
            field=models.CharField(max_length=100),
        ),
    ]
