# Generated by Django 2.2 on 2019-06-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20190604_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='EHS_training',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='leave',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='security_training',
            field=models.DateField(blank=True),
        ),
    ]
