# Generated by Django 2.2 on 2019-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20190604_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='culture_room_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='culture_room_start',
            field=models.DateField(blank=True),
        ),
    ]
