# Generated by Django 2.2 on 2019-06-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20190604_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='EHS_training',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='culture_room_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='culture_room_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='leave',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='security_training',
            field=models.DateField(blank=True, null=True),
        ),
    ]
