# Generated by Django 2.2 on 2019-06-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20190604_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='card_pi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
