# Generated by Django 2.2 on 2019-06-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20190610_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='extension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
