# Generated by Django 2.2 on 2019-06-11 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20190610_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
