# Generated by Django 2.2 on 2019-06-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20190611_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='core_lab',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('PI', 'PI'), ('Staff', 'Staff')], max_length=5, null=True),
        ),
    ]
