# Generated by Django 2.2 on 2019-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20190612_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='access_card',
            field=models.BooleanField(default=False),
        ),
    ]
