# Generated by Django 2.2 on 2019-06-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20190618_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alt_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='employee_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
