# Generated by Django 2.2 on 2019-06-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20190618_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='culture_room',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='extension_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='extension_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='hazardous_chemicals',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='pass_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='pre_extension_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='pre_extension_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='toxic_chenicals',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
