# Generated by Django 2.2 on 2019-06-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20190619_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='EHS_training',
            new_name='EHS_training_date',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='leave',
            new_name='leave_date',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='security_training',
            new_name='security_training_date',
        ),
        migrations.AlterField(
            model_name='staff',
            name='permanent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
