# Generated by Django 2.2 on 2019-06-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20190619_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='extension_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='pre_extension_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
