# Generated by Django 2.2 on 2019-06-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_auto_20190619_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='property',
            field=models.CharField(blank=True, choices=[('醫研部', '醫研部'), ('固定', '固定'), ('流動', '流動')], max_length=100, null=True),
        ),
    ]
