# Generated by Django 2.2 on 2019-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_auto_20190619_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='pass_date',
            field=models.DateField(blank=True, default='0000-00-00', null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='return_date',
            field=models.DateField(blank=True, default='0000-00-00', null=True),
        ),
    ]
