# Generated by Django 2.2 on 2019-06-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_auto_20190619_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='school',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='culture_room',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
