# Generated by Django 2.2 on 2019-06-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_auto_20190620_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_ID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='receipt',
            field=models.CharField(max_length=20),
        ),
    ]
