# Generated by Django 2.2 on 2019-06-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_auto_20190620_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='receive',
            new_name='receive_date',
        ),
    ]
