# Generated by Django 2.2 on 2019-06-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_auto_20190620_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
