# Generated by Django 2.2 on 2019-06-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_card_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='inner_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='serial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
