# Generated by Django 2.2 on 2019-06-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_auto_20190620_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_PI',
        ),
    ]
