# Generated by Django 2.2 on 2019-06-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_remove_card_card_pi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='uid',
        ),
    ]
