# Generated by Django 2.2 on 2019-06-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_remove_card_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='uid',
            field=models.OneToOneField(default='3f6ba1b3-4eda-47d2-a686-8eaf0fbf7230', on_delete=django.db.models.deletion.CASCADE, to='database.Person'),
            preserve_default=False,
        ),
    ]
