# Generated by Django 2.2 on 2019-06-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0048_auto_20190621_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='pi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
