# Generated by Django 2.2 on 2019-06-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0049_auto_20190621_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='card_pi_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pi_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
