# Generated by Django 2.2 on 2019-06-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_auto_20190624_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='remark',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
