# Generated by Django 2.2 on 2019-06-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_person_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
    ]
