# Generated by Django 2.2 on 2019-06-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_auto_20190628_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_ID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='卡號'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='身份證'),
        ),
        migrations.AlterField(
            model_name='card',
            name='inner_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='內碼'),
        ),
        migrations.AlterField(
            model_name='card',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='card',
            name='receipt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='收據號碼'),
        ),
        migrations.AlterField(
            model_name='card',
            name='remark',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='card',
            name='serial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='序號'),
        ),
        migrations.AlterField(
            model_name='person',
            name='access_card',
            field=models.BooleanField(default=False, verbose_name='領用門禁卡'),
        ),
        migrations.AlterField(
            model_name='person',
            name='alt_mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='次要信箱'),
        ),
        migrations.AlterField(
            model_name='person',
            name='core_lab',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1, null=True, verbose_name='共研'),
        ),
        migrations.AlterField(
            model_name='person',
            name='employee_ID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extension',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='分機'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='職稱'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='主要信箱'),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='簡碼'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='單位'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手機'),
        ),
        migrations.AlterField(
            model_name='person',
            name='remark',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('PI', 'PI'), ('Staff', 'Staff')], max_length=5, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='連絡窗口'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='culture_room',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='使用細胞室'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='extension_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='當年度展延日期'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='extension_result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='當年度展延結果'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='hazardous_chemicals',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='使用危害性化學品'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='pass_date',
            field=models.DateField(blank=True, null=True, verbose_name='審核通過日'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='pre_extension_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='前一年度展延日期'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='pre_extension_result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='前一年度展延結果'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='property',
            field=models.CharField(blank=True, choices=[('醫研部', '醫研部'), ('固定', '固定'), ('流動', '流動')], max_length=100, null=True, verbose_name='性質'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='歸還日'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='toxic_chenicals',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='使用毒化物'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='EHS_training',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='環安衛教育訓練'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='EHS_training_date',
            field=models.DateField(blank=True, null=True, verbose_name='環安衛教育訓練日期'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='card_pi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='門禁卡PI(uid)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='card_pi_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='門禁卡PI'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='culture_room',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='細胞室'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='culture_room_end',
            field=models.DateField(blank=True, null=True, verbose_name='細胞室停用日期'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='culture_room_start',
            field=models.DateField(blank=True, null=True, verbose_name='細胞室使用日期'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='leave',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='離職'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='離職日期'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='permanent',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='常駐'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='人事資料卡PI(uid)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pi_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='人事資料卡PI'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='上課'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='security_training',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='生安教育訓練'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='security_training_date',
            field=models.DateField(blank=True, null=True, verbose_name='生安教育訓練日期'),
        ),
    ]
