# Generated by Django 2.2 on 2019-06-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_auto_20190628_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('PI', 'PI'), ('Staff', 'Staff')], max_length=5, null=True, verbose_name='類別'),
        ),
    ]
