# Generated by Django 2.2 on 2019-06-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0054_auto_20190628_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Person', verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Person', verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Person', verbose_name='姓名'),
        ),
    ]
