# Generated by Django 2.2 on 2019-07-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0055_auto_20190628_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pi',
            old_name='property',
            new_name='pi_property',
        ),
    ]
