# Generated by Django 2.2 on 2019-07-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0056_auto_20190703_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pi',
            old_name='pi_property',
            new_name='property',
        ),
    ]
