# Generated by Django 2.2 on 2019-07-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0057_auto_20190703_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='corelab_class',
            field=models.BooleanField(default=False, verbose_name='共研講習'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='culture_room',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='細胞室'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='hazardous_chemicals',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='危害物'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='toxic_chenicals',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='毒化物'),
        ),
    ]
