# Generated by Django 2.2 on 2019-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0058_auto_20190703_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='culture_room',
            field=models.BooleanField(default=False, verbose_name='細胞室'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='hazardous_chemicals',
            field=models.BooleanField(default=False, verbose_name='危害物'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='toxic_chenicals',
            field=models.BooleanField(default=False, verbose_name='毒化物'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='EHS_training',
            field=models.BooleanField(default=False, verbose_name='環安衛教育訓練'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='culture_room',
            field=models.BooleanField(default=False, verbose_name='細胞室'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='leave',
            field=models.BooleanField(default=False, verbose_name='離職'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='permanent',
            field=models.BooleanField(default=False, verbose_name='常駐'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.BooleanField(default=False, verbose_name='上課'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='security_training',
            field=models.BooleanField(default=False, verbose_name='生安教育訓練'),
        ),
    ]
