# Generated by Django 2.2 on 2019-07-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_auto_20190703_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='corelab_class',
        ),
    ]
