# Generated by Django 2.2 on 2019-07-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0060_remove_staff_corelab_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_receive',
            field=models.DateField(blank=True, null=True, verbose_name='領卡日期'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_return',
            field=models.DateField(blank=True, null=True, verbose_name='退卡日期'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='EHS_training',
            field=models.BooleanField(default=False, verbose_name='共研講習'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='EHS_training_date',
            field=models.DateField(blank=True, null=True, verbose_name='共研講習日期'),
        ),
    ]
