# Generated by Django 2.2 on 2019-07-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0061_auto_20190703_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='info',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RAs', to='database.PI', verbose_name='人資PI'),
        ),
    ]
