# Generated by Django 2.2 on 2019-07-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_staff_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='info',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RAs', to='database.PI', verbose_name='人資PI'),
        ),
    ]
