# Generated by Django 2.2 on 2019-07-05 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_auto_20190705_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='database.Person', verbose_name='姓名'),
        ),
    ]
