# Generated by Django 2.2 on 2019-07-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_auto_20190705_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='info_card',
            field=models.CharField(blank=True, choices=[('已交', '已交'), ('未交', '未交'), ('不用交', '不用交')], max_length=100, null=True, verbose_name='人事資料卡'),
        ),
    ]
