# Generated by Django 2.2 on 2019-07-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0067_staff_info_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='card',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_RAs', to='database.PI', verbose_name='門禁卡PI'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='info',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RAs', to='database.PI', verbose_name='人資卡PI'),
        ),
    ]
