# Generated by Django 2.2 on 2019-07-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0068_auto_20190712_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pi',
            name='contact',
        ),
    ]
