# Generated by Django 2.2 on 2019-07-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0070_pi_contact_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pi',
            old_name='contact_method',
            new_name='contact',
        ),
    ]
