# Generated by Django 2.2 on 2019-07-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0071_auto_20190712_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pi',
            name='contact',
        ),
    ]
