# Generated by Django 2.2 on 2019-07-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0072_remove_pi_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='database.Staff', verbose_name='聯絡窗口'),
        ),
    ]
