# Generated by Django 2.2 on 2019-07-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0073_pi_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pi',
            name='contact',
        ),
    ]
