# Generated by Django 2.2 on 2019-08-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0075_pi_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='EHS_training',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='permanent',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='school',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='security_training',
        ),
    ]
