# Generated by Django 2.2 on 2019-09-17 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0076_auto_20190807_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='leave',
            field=models.BooleanField(default=False, verbose_name='離職'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='info',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RAs', to='database.PI', verbose_name='人事資料卡PI'),
        ),
    ]
